<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Worker\Module'                       => __DIR__ . '/Module.php',
  'Worker\Controller\IndexController'   => __DIR__ . '/src/Worker/Controller/IndexController.php',
  'Worker\Entity\Worker'                => __DIR__ . '/src/Worker/Entity/Worker.php',
  'Worker\Factory\WorkerAddFormFactory' => __DIR__ . '/src/Worker/Factory/WorkerAddFormFactory.php',
  'Worker\Form\AddWorkerFieldset'       => __DIR__ . '/src/Worker/Form/AddWorkerFieldset.php',
  'Worker\Form\AddWorkerForm'           => __DIR__ . '/src/Worker/Form/AddWorkerForm.php',
  'Worker\Repository\WorkerRepository'  => __DIR__ . '/src/Worker/Repository/WorkerRepository.php',
  'Worker\Service\Worker'               => __DIR__ . '/src/Worker/Service/Worker.php',
);
