<?php
echo $this->inlineScript()->prependFile($this->basePath('js/main.js'), 'text/javascript')
    ->prependFile($this->basePath('js/lib.js'), 'text/javascript')
    ->prependFile($this->basePath('js/glDatePicker.min.js', 'text/javascript'))
    ->prependFile($this->basePath('js/jquery.form.min.js', 'text/javascript'))
    ->prependFile($this->basePath('js/jquery.datetimepicker.js', 'text/javascript'))
    ->prependFile($this->basePath('js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9')))
    ->prependFile($this->basePath('js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9')))
    ->prependFile($this->basePath('js/jquery-1.11.0.min.js', 'text/javascript'));
?>