<head>
    <?php
    $child = $this->child;
    $isMobile = $this->mobile();
    $pageTitle = (isset($child->pageTitle)) ? $child->pageTitle : "Scheduler";
    $follow = (isset($child->follow)) ? "noindex, nofollow" : "feed, follow, archieve";

    // The website's title.
    echo $this->headTitle($pageTitle);

    // The meta tags
    $description = isset($child->metaInfo['description']) ? $child->metaInfo['description'] : 'The scheduler description.';
    $keywords = isset($child->metaInfo['keywords']) ? $child->metaInfo['keywords'] : 'the, scheduler, tags';

    // We append everything to the headMeta
    $this->headMeta()
        ->setCharset('UTF-8')
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ->appendName('description', $description)
        ->appendName('keywords', $keywords)
        ->appendName('robots', $follow)
        ->appendName('language', 'en')
        ->appendName('googlebot', $follow);
       # ->appendProperty('fb:app_id', '268335233334900')
       # ->appendProperty('fb:admins', '1124061431')
    echo $this->headMeta();

    // We add the favicon and our stylesheets
    $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath('images/favicon.ico')))
        ->prependStylesheet($this->basePath('css/glDatePicker.default.css'))
        ->prependStylesheet($this->basePath('css/glDatePicker.flatwhite.css'))
        ->prependStylesheet($this->basePath('css/jquery.datetimepicker.css'))
        ->prependStylesheet($this->basePath('css/style.css'));

    if ($isMobile) {
        $this->headLink()->appendStylesheet($this->basePath('css/mobile.css'));
    }
    echo $this->headLink();

    // Some scripts the must be outputted first follow below
    ?>
    <script>
        var baseUrl = '<?php echo $this->basePath(); ?>';
        var isMobile = <?php echo $isMobile ? 'true':'false'; ?>;
    </script>
</head>