<?php
$form->prepare();
/**
 * @var \Zend\Form\Fieldset $fieldset
 */
$fieldset = $form->get('worker');
$form->setAttribute('action', $this->url('workers/add'));
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('security'));
?>
<table>
    <caption><?php echo $this->translate("Add a New Worker");?></caption>
    <thead>
    <tr>
        <th><?php echo $this->translate("Name");?>*</th>
        <th><?php echo $this->translate("Surname");?>*</th>
        <th><?php echo $this->translate("Position");?></th>
        <th><?php echo $this->translate("Email");?></th>
        <th><?php echo $this->translate("Address");?></th>
        <th><?php echo $this->translate("First Telephone");?></th>
        <th><?php echo $this->translate("Second Telephone");?></th>
        <th><?php echo $this->translate("Hire Date");?></th>
        <th><?php echo $this->translate("Release Date");?></th>
        <th><?php echo $this->translate("Work Hours");?></th>
        <th><?php echo $this->translate("Salary");?></th>
        <th><?php echo $this->translate("Notes");?></th>
        <th><?php echo $this->translate("Add");?></th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>
            <?php
            echo $this->formInput($fieldset->get('name'));
            echo $this->formElementErrors($fieldset->get('name'), array('class' => 'formError'));
            ?>
        </td>
        <td>
            <?php
            echo $this->formInput($fieldset->get('surname'));
            echo $this->formElementErrors($fieldset->get('surname'), array('class' => 'formError'));
            ?>
        </td>
        <td>
            <?php
            echo $this->formInput($fieldset->get('position'));
            echo $this->formElementErrors($fieldset->get('position'), array('class' => 'formError'));
            ?>
        </td>
        <td>
            <?php
            echo $this->formInput($fieldset->get('email'));
            echo $this->formElementErrors($fieldset->get('email'), array('class' => 'formError'));
            ?>
        </td>
        <td>
            <?php
            echo $this->formInput($fieldset->get('address'));
            echo $this->formElementErrors($fieldset->get('address'), array('class' => 'formError'));
            ?>
        </td>
        <td>
            <?php
            echo $this->formInput($fieldset->get('firstTelephone'));
            echo $this->formElementErrors($fieldset->get('firstTelephone'), array('class' => 'formError'));
            ?>
        </td>
        <td>
            <?php
            echo $this->formInput($fieldset->get('secondTelephone'));
            echo $this->formElementErrors($fieldset->get('secondTelephone'), array('class' => 'formError'));
            ?>
        </td>
        <td>
            <?php
            echo $this->formInput($fieldset->get('hireDate'), array('class','formDate'));
            echo $this->formElementErrors($fieldset->get('hireDate'), array('class' => 'formError'));
            ?>
        </td>
        <td>
            <?php
            echo $this->formInput($fieldset->get('releaseDate'), array('class','formDate'));
            echo $this->formElementErrors($fieldset->get('releaseDate'), array('class' => 'formError'));
            ?>
        </td>
        <td>
            <?php
            echo $this->formInput($fieldset->get('workHours'));
            echo $this->formElementErrors($fieldset->get('workHours'), array('class' => 'formError'));
            ?>
        </td>
        <td>
            <?php
            echo $this->formInput($fieldset->get('salary'));
            echo $this->formElementErrors($fieldset->get('salary'), array('class' => 'formError'));
            ?>
        </td>
        <td>
            <?php
            echo $this->formTextarea($fieldset->get('notes'));
            echo $this->formElementErrors($fieldset->get('notes'), array('class' => 'formError'));
            ?>
        </td>
        <td>
            <?php echo $this->formSubmit($form->get('submit')->setValue($this->translate('Add'))); ?>
        </td>
    </tr>
    </tbody>
</table>
<?php echo $this->form()->closeTag() ?>
