<div id="optionPanel">
    <span class="addWorkerToggle">+ <?php echo $this->translate("Add Worker"); ?></span>
    <span id="saveChanges"><?php echo $this->translate("Save"); ?></span>
    <span id="resetChanges"><?php echo $this->translate("Reset"); ?></span>
</div>
<div id="addWorker">
    <?php
    $form->prepare();
    /**
     * @var \Zend\Form\Fieldset $fieldset
     */
    $fieldset = $form->get('worker');
    $form->setAttribute('action', $this->url('workers/add'));
    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('security'));
    ?>
    <table>
        <caption><?php echo $this->translate("Add a New Worker"); ?></caption>
        <thead>
        <tr>
            <th><?php echo $this->translate("Name"); ?>*</th>
            <th><?php echo $this->translate("Surname"); ?>*</th>
            <th><?php echo $this->translate("Position"); ?></th>
            <th><?php echo $this->translate("Email"); ?></th>
            <th><?php echo $this->translate("Address"); ?></th>
            <th><?php echo $this->translate("First Telephone"); ?></th>
            <th><?php echo $this->translate("Second Telephone"); ?></th>
            <th><?php echo $this->translate("Hire Date"); ?></th>
            <th><?php echo $this->translate("Release Date"); ?></th>
            <th><?php echo $this->translate("Work Hours"); ?></th>
            <th><?php echo $this->translate("Salary"); ?></th>
            <th><?php echo $this->translate("Notes"); ?></th>
            <th><?php echo $this->translate("Add"); ?></th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>
                <?php
                echo $this->formInput($fieldset->get('name'));
                echo $this->formElementErrors($fieldset->get('name'), array('class' => 'formError'));
                ?>
            </td>
            <td>
                <?php
                echo $this->formInput($fieldset->get('surname'));
                echo $this->formElementErrors($fieldset->get('surname'), array('class' => 'formError'));
                ?>
            </td>
            <td>
                <?php
                echo $this->formInput($fieldset->get('position'));
                echo $this->formElementErrors($fieldset->get('position'), array('class' => 'formError'));
                ?>
            </td>
            <td>
                <?php
                echo $this->formInput($fieldset->get('email'));
                echo $this->formElementErrors($fieldset->get('email'), array('class' => 'formError'));
                ?>
            </td>
            <td>
                <?php
                echo $this->formInput($fieldset->get('address'));
                echo $this->formElementErrors($fieldset->get('address'), array('class' => 'formError'));
                ?>
            </td>
            <td>
                <?php
                echo $this->formInput($fieldset->get('firstTelephone'));
                echo $this->formElementErrors($fieldset->get('firstTelephone'), array('class' => 'formError'));
                ?>
            </td>
            <td>
                <?php
                echo $this->formInput($fieldset->get('secondTelephone'));
                echo $this->formElementErrors($fieldset->get('secondTelephone'), array('class' => 'formError'));
                ?>
            </td>
            <td>
                <?php
                echo $this->formInput($fieldset->get('hireDate'));
                echo $this->formElementErrors($fieldset->get('hireDate'), array('class' => 'formError'));
                ?>
            </td>
            <td>
                <?php
                echo $this->formInput($fieldset->get('releaseDate'));
                echo $this->formElementErrors($fieldset->get('releaseDate'), array('class' => 'formError'));
                ?>
            </td>
            <td>
                <?php
                echo $this->formInput($fieldset->get('workHours'));
                echo $this->formElementErrors($fieldset->get('workHours'), array('class' => 'formError'));
                ?>
            </td>
            <td>
                <?php
                echo $this->formInput($fieldset->get('salary'));
                echo $this->formElementErrors($fieldset->get('salary'), array('class' => 'formError'));
                ?>
            </td>
            <td>
                <?php
                echo $this->formTextarea($fieldset->get('notes'));
                echo $this->formElementErrors($fieldset->get('notes'), array('class' => 'formError'));
                ?>
            </td>
            <td>
                <?php echo $this->formSubmit($form->get('submit')->setValue($this->translate('Add'))); ?>
            </td>
        </tr>
        </tbody>
    </table>
    <?php echo $this->form()->closeTag() ?>
</div>
<div class="tableWrapper">
    <table id="workers" class="editableTable">
        <?php
        for ($i = 0; $i < 13; $i++)
            echo '<colgroup></colgroup>';
        ?>
        <thead>
        <tr>
            <th class="invisible">Id</th>
            <th><?php echo $this->translate("Name"); ?></th>
            <th><?php echo $this->translate("Surname"); ?></th>
            <th><?php echo $this->translate("Position"); ?></th>
            <th><?php echo $this->translate("Email"); ?></th>
            <th><?php echo $this->translate("Address"); ?></th>
            <th><?php echo $this->translate("First Telephone"); ?></th>
            <th><?php echo $this->translate("Second Telephone"); ?></th>
            <th><?php echo $this->translate("Hire Date"); ?></th>
            <th><?php echo $this->translate("Release Date"); ?></th>
            <th><?php echo $this->translate("Work Hours"); ?></th>
            <th><?php echo $this->translate("Salary"); ?></th>
            <th><?php echo $this->translate("Notes"); ?></th>
            <th><?php echo $this->translate("Delete"); ?></th>
        </tr>
        </thead>
        <tbody>
        <?php
        /**
         * @var \Worker\Entity\Worker $worker
         */
        foreach ($this->workers as $worker): ?>
            <tr>
                <td class="workerWorkerId invisible"><?php echo $worker->getWorkerId(); ?></td>
                <td class="workerName editText"><?php echo $worker->getName(); ?></td>
                <td class="workerSurname editText"><?php echo $worker->getSurname(); ?></td>
                <td class="workerPosition editText"><?php echo $worker->getPosition(); ?></td>
                <td class="workerEmail editText"><?php echo $worker->getEmail(); ?></td>
                <td class="workerAddress editText"><?php echo $worker->getAddress(); ?></td>
                <td class="workerFirstTelephone editText"><?php echo $worker->getFirstTelephone(); ?></td>
                <td class="workerSecondTelephone editText"><?php echo $worker->getSecondTelephone(); ?></td>
                <td class="workerHireDate editDatetime"><?php echo is_null($worker->getHireDate()) ? '' : $worker->getHireDate()->format('d-m-Y'); ?></td>
                <td class="workerReleaseDate editDatetime"><?php echo is_null($worker->getReleaseDate()) ? '' : $worker->getReleaseDate()->format('d-m-Y'); ?></td>
                <td class="workerWorkHours editText"><?php echo $worker->getWorkHours(); ?></td>
                <td class="workerSalary editText"><?php echo $worker->getSalary(); ?></td>
                <td class="workerNotes editText"><?php echo $worker->getNotes(); ?></td>
                <td class="delete">X</td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
<div id="editPanel">
    <textarea class="editInput"></textarea>
    <span id="editDone"><?php echo $this->translate("Done"); ?></span>
</div>