<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Admin\Module'                      => __DIR__ . '/Module.php',
  'Admin\Controller\IndexController'  => __DIR__ . '/src/Admin/Controller/IndexController.php',
  'Admin\Entity\Admin'                => __DIR__ . '/src/Admin/Entity/Admin.php',
  'Admin\Factory\AdminAddFormFactory' => __DIR__ . '/src/Admin/Factory/AdminAddFormFactory.php',
  'Admin\Form\AddAdminFieldset'       => __DIR__ . '/src/Admin/Form/AddAdminFieldset.php',
  'Admin\Form\AddAdminForm'           => __DIR__ . '/src/Admin/Form/AddAdminForm.php',
  'Admin\Service\Admin'               => __DIR__ . '/src/Admin/Service/Admin.php',
);
