<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Application\Module'                          => __DIR__ . '/Module.php',
  'Application\Controller\IndexController'      => __DIR__ . '/src/Application/Controller/IndexController.php',
  'Application\Factory\ActionNameHelperFactory' => __DIR__ . '/src/Application/Factory/ActionNameHelperFactory.php',
  'Application\Factory\AdminPluginFactory'      => __DIR__ . '/src/Application/Factory/AdminPluginFactory.php',
  'Application\Factory\AdminViewHelperFactory'  => __DIR__ . '/src/Application/Factory/AdminViewHelperFactory.php',
  'Application\Factory\AuthFactory'             => __DIR__ . '/src/Application/Factory/AuthFactory.php',
  'Application\Factory\LoginFormFactory'        => __DIR__ . '/src/Application/Factory/LoginFormFactory.php',
  'Application\Form\LoginFieldset'              => __DIR__ . '/src/Application/Form/LoginFieldset.php',
  'Application\Form\LoginForm'                  => __DIR__ . '/src/Application/Form/LoginForm.php',
  'Application\Model\AuthStorage'               => __DIR__ . '/src/Application/Model/AuthStorage.php',
  'Application\Plugin\ActiveAdmin'              => __DIR__ . '/src/Application/Plugin/ActiveAdmin.php',
  'Application\View\Helper\ActionName'          => __DIR__ . '/src/Application/View/Helper/ActionName.php',
  'Application\View\Helper\Admin'               => __DIR__ . '/src/Application/View/Helper/Admin.php',
  'Application\View\Helper\Mobile'              => __DIR__ . '/src/Application/View/Helper/Mobile.php',
);
