<?php
$form->prepare();
/**
 * @var \Zend\Form\Fieldset $fieldset
 */
$fieldset = $form->get('exception');
$form->setAttribute('action', $this->url('exceptions/add'));
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('security'));
?>
<table>
    <caption><?php echo $this->translate("Add a New Entry"); ?></caption>
    <thead>
    <tr>
        <th><?php echo $this->translate("Name"); ?>*</th>
        <th><?php echo $this->translate("Color"); ?>*</th>
        <th><?php echo $this->translate("Add"); ?></th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>
            <?php
            echo $this->formInput($fieldset->get('name'));
            echo $this->formElementErrors($fieldset->get('name'), array('class' => 'formError'));
            ?>
        </td>
        <td>
            <?php
            echo $this->formSelect($fieldset->get('color'));
            echo $this->formElementErrors($fieldset->get('color'), array('class' => 'formError'));
            ?>
        </td>
        <td>
            <?php echo $this->formSubmit($form->get('submit')->setValue($this->translate('Add'))); ?>
        </td>
    </tr>
    </tbody>
</table>
<?php echo $this->form()->closeTag() ?>
