<?php
$form->prepare();
$form->setAttribute('action', $this->url('exceptions/add'));
$fieldset = $form->get('exception');
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('security'));
?>
<table>
    <caption>Add a New Entry</caption>
    <thead>
    <tr>
        <th>Name*</th>
        <th>Referenced Date</th>
        <th>Add</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>
            <?php
            echo $this->formInput($fieldset->get('name'));
            echo $this->formElementErrors($fieldset->get('name'), array('class' => 'formError'));
            ?>
        </td>
        <td>
            <?php
            echo $this->formInput($fieldset->get('referencedDate'));
            echo $this->formElementErrors($fieldset->get('referencedDate'), array('class' => 'formError'));
            ?>
        </td>
        <td>
            <?php echo $this->formSubmit($form->get('submit')->setValue($this->translate('Add'))); ?>
        </td>
    </tr>
    </tbody>
</table>
<?php echo $this->form()->closeTag() ?>
