<div id="optionPanel">
    <span class="addExceptionToggle">+ <?php echo $this->translate("Add New Exception"); ?></span>
    <span id="saveChanges"><?php echo $this->translate("Save"); ?></span>
    <span id="resetChanges"><?php echo $this->translate("Reset"); ?></span>
</div>
<div id="addException">
    <?php
    $form->prepare();
    /**
     * @var \Zend\Form\Fieldset $fieldset
     */
    $fieldset = $form->get('exception');
    $form->setAttribute('action', $this->url('exceptions/add'));
    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('security'));
    ?>
    <table>
        <caption><?php echo $this->translate("Add a New Exception"); ?></caption>
        <thead>
        <tr>
            <th><?php echo $this->translate("Name"); ?>*</th>
            <th><?php echo $this->translate("Color"); ?>*</th>
            <th><?php echo $this->translate("Add"); ?></th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>
                <?php
                echo $this->formInput($fieldset->get('name'));
                echo $this->formElementErrors($fieldset->get('name'), array('class' => 'formError'));
                ?>
            </td>
            <td>
                <?php
                echo $this->formSelect($fieldset->get('color'));
                echo $this->formElementErrors($fieldset->get('color'), array('class' => 'formError'));
                ?>
            </td>
            <td>
                <?php echo $this->formSubmit($form->get('submit')->setValue($this->translate('Add'))); ?>
            </td>
        </tr>
        </tbody>
    </table>
    <?php echo $this->form()->closeTag() ?>

</div>
<div class="tableWrapper">
    <table id="exceptions" class="editableTable">
        <?php
        for ($i = 0; $i < 3; $i++)
            echo '<colgroup></colgroup>';
        ?>
        <thead>
        <tr>
            <th class="invisible">Color Id</th>
            <th><?php echo $this->translate("Name"); ?></th>
            <th><?php echo $this->translate("Color"); ?></th>
            <th><?php echo $this->translate("Delete"); ?></th>
        </tr>
        </thead>
        <tbody>
        <?php
        /**
         * @var \Schedule\Entity\Exception $exception
         */
        foreach ($this->exceptions as $exception):
            $color = $exception->getColor();
            ?>
            <tr>
                <td class="exceptionExceptionId invisible"><?php echo $exception->getExceptionId(); ?></td>
                <td class="exceptionName editText"><?php echo $exception->getName(); ?></td>
                <td class="exceptionColor editColor" style="color:<?php echo $color; ?>"><?php echo $color; ?></td>
                <td class="delete">X</td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
<div id="editPanel">
    <textarea class="editInput"></textarea>
    <span id="editDone"><?php echo $this->translate("Done"); ?></span>
</div>