<div id="optionPanel">
    <span id="addExceptionToggle">
        + Add New Exception
    </span>
    <span id="saveChanges">
        Save
    </span>
    <span id="resetChanges">
        Reset
    </span>
</div>
<div id="addException"<?php echo $hideForm ? ' class="invisible"':'';?>>
    <?php
    $form->prepare();
    $form->setAttribute('action', $this->url('exceptions/add'));
    $fieldset = $form->get('exception');
    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('security'));
    ?>
    <table>
        <caption>Add a New Exception</caption>
        <thead>
        <tr>
            <th>Name*</th>
            <th>Referenced Date</th>
            <th>Add</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>
                <?php
                echo $this->formInput($fieldset->get('name'));
                echo $this->formElementErrors($fieldset->get('name'), array('class' => 'formError'));
                ?>
            </td>
            <td>
                <?php
                echo $this->formInput($fieldset->get('referencedDate'));
                echo $this->formElementErrors($fieldset->get('referencedDate'), array('class' => 'formError'));
                ?>
            </td>
            <td>
                <?php echo $this->formSubmit($form->get('submit')->setValue($this->translate('Add'))); ?>
            </td>
        </tr>
        </tbody>
    </table>
    <?php echo $this->form()->closeTag() ?>

</div>
<table id="exceptions" class="editableTable">
    <caption>Exceptions</caption>
    <?php
    for ($i = 0; $i < 3; $i++)
        echo '<colgroup></colgroup>';
    ?>
    <thead>
    <tr>
        <th>Name</th>
        <th>Referenced Date</th>
        <th>Delete</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($exceptions as $exception): ?>
        <tr>
            <td class="exceptionExceptionId invisible"><?php echo $exception->getExceptionId(); ?></td>
            <td class="exceptionName editText"><?php echo $exception->getName(); ?></td>
            <td class="exceptionReferencedDate editDatetime"><?php echo $exception->getReferencedDate() != null ? $exception->getReferencedDate()->format('d-m-Y') : ''; ?></td>
            <td class="delete">X</td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<div id="editPanel">
    <textarea></textarea>
    <span id="editDone">Done</span>
</div>