<?php
echo $this->doctype();
$children = $this->viewModel()->getCurrent()->getChildren();
$child = $children[0];
?>
<html lang="en">
<?php
// The layout's head
echo $this->partial("header", array('child' => $child));
?>
<body<?php echo ($child->bodyClass) ? ' class="' . $child->bodyClass . '"' : ''; ?>>
<noscript>
    <div id="nojs">
        <?php echo $this->translate("Please enable javascript for the site to work properly."); ?>
    </div>
</noscript>
<?php
$messages = $this->flashMessenger()->getMessages();
$clearMessages = array();
if (!empty($messages)) :
    ?>
    <div id="flash">
        <ul class="flashMessages">
            <?php foreach ($messages as $fMessage) : ?>
                <li><?php echo $fMessage; ?></li>
            <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>
<?php if ($this->identity()):
    $route = $this->actionName(); ?>
    <header>
        <nav>
            <ul>
                <li><a href="<?php echo $this->url('workers'); ?>"<?php echo $route == "workers" ? ' class="active"' : ''; ?>><?php echo $this->translate("Workers"); ?></a></li>
                <li><a href="<?php echo $this->url('schedule'); ?>"<?php echo $route == "schedule" ? ' class="active"' : ''; ?>><?php echo $this->translate("Schedule"); ?></a></li>
                <li><a href="<?php echo $this->url('admins'); ?>"<?php echo $route == "admins" ? ' class="active"' : ''; ?>><?php echo $this->translate("Admins"); ?></a></li>
                <li><a href="<?php echo $this->url('changelogs'); ?>"<?php echo $route == "changelogs" ? ' class="active"' : ''; ?>><?php echo $this->translate("Changelogs"); ?></a></li>
                <li><a href="<?php echo $this->url('exceptions'); ?>"<?php echo $route == "exceptions" ? ' class="active"' : ''; ?>><?php echo $this->translate("Exceptions"); ?></a></li>
                <li><a href="<?php echo $this->url('logout'); ?>"><?php echo $this->translate("Logout"); ?></a></li>
            </ul>
        </nav>
    </header>
<?php endif; ?>
<div id="content">
    <?php echo $this->content; ?>
</div>
<?php
// The layout's footer
echo $this->partial("footer", array('child' => $child));
?>
</body>
</html>
