<?php
$form->prepare();
/**
 * @var \Zend\Form\Fieldset $fieldset
 */
$fieldset = $form->get('entry');
$form->setAttribute('action', $this->url('schedule_add'));
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('security'));
?>
<table>
    <caption><?php echo $this->translate("Add a New Entry"); ?></caption>
    <thead>
    <tr>
        <th><?php echo $this->translate("Worker"); ?>*</th>
        <th><?php echo $this->translate("Exception"); ?></th>
        <th><?php echo $this->translate("Start Time"); ?>*</th>
        <th><?php echo $this->translate("End Time"); ?>*</th>
        <th><?php echo $this->translate("Add"); ?></th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>
            <?php
            echo $this->formSelect($fieldset->get('worker'));
            echo $this->formElementErrors($fieldset->get('worker'), array('class' => 'formError'));
            ?>
        </td>
        <td>
            <?php
            echo $this->formSelect($fieldset->get('exception'));
            echo $this->formElementErrors($fieldset->get('exception'), array('class' => 'formError'));
            ?>
        </td>
        <td>
            <?php
            echo $this->formInput($fieldset->get('startTime'));
            echo $this->formElementErrors($fieldset->get('startTime'), array('class' => 'formError'));
            ?>
        </td>
        <td>
            <?php
            echo $this->formInput($fieldset->get('endTime'));
            echo $this->formElementErrors($fieldset->get('endTime'), array('class' => 'formError'));
            ?>
        </td>
        <td>
            <?php echo $this->formSubmit($form->get('submit')->setValue($this->translate('Add'))); ?>
        </td>
    </tr>
    </tbody>
</table>
<?php echo $this->form()->closeTag() ?>
