<div id="optionPanel">
    <span class="dateRangeToggle"><?php echo $this->translate("Select Date Range"); ?></span>
    <?php if ($this->identity()): ?>
        <span class="addEntryToggle">+ <?php echo $this->translate("Add New Entry"); ?></span>
        <span id="saveChanges"><?php echo $this->translate("Save"); ?></span>
        <span id="resetChanges"><?php echo $this->translate("Reset"); ?></span>
    <?php endif; ?>
    <a href="<?php echo $this->url('schedule_export',array('startDate' => $startDate->format('d-m-Y'),'endDate' => $endDate->format('d-m-Y'))); ?>"><?php echo $this->translate("Export Excel"); ?></a>
</div>
<div id="dateRange" class="invisible">
    <h2><?php echo $this->translate("Select a Date Range"); ?></h2>
    <span><?php echo $this->translate("From"); ?></span>
    <input type="text" id="dateRangeStart"/>
    <span><?php echo $this->translate("To"); ?></span>
    <input type="text" id="dateRangeEnd"/>
    <span class="button"><?php echo $this->translate("Show"); ?></span>
</div>
<?php if ($this->identity()): ?>
    <div id="addEntry">
        <?php
        $form->prepare();
        /**
         * @var \Zend\Form\Fieldset $fieldset
         */
        $fieldset = $form->get('entry');
        $form->setAttribute('action', $this->url('schedule_add'));
        echo $this->form()->openTag($form);
        echo $this->formHidden($form->get('security'));
        echo $this->formHidden($fieldset->get('entryId'));
        ?>
        <table>
            <caption><?php echo $this->translate("Add a New Entry"); ?></caption>
            <thead>
            <tr>
                <th><?php echo $this->translate("Worker"); ?>*</th>
                <th><?php echo $this->translate("Exception"); ?></th>
                <th><?php echo $this->translate("Start Time"); ?>*</th>
                <th><?php echo $this->translate("End Time"); ?>*</th>
                <th><?php echo $this->translate("Add"); ?></th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>
                    <?php
                    echo $this->formSelect($fieldset->get('worker'));
                    echo $this->formElementErrors($fieldset->get('worker'), array('class' => 'formError'));
                    ?>
                </td>
                <td>
                    <?php
                    echo $this->formSelect($fieldset->get('exception'));
                    echo $this->formElementErrors($fieldset->get('exception'), array('class' => 'formError'));
                    ?>
                </td>
                <td>
                    <?php
                    echo $this->formInput($fieldset->get('startTime'));
                    echo $this->formElementErrors($fieldset->get('startTime'), array('class' => 'formError'));
                    ?>
                </td>
                <td>
                    <?php
                    echo $this->formInput($fieldset->get('endTime'));
                    echo $this->formElementErrors($fieldset->get('endTime'), array('class' => 'formError'));
                    ?>
                </td>
                <td>
                    <?php echo $this->formSubmit($form->get('submit')->setValue($this->translate('Add'))); ?>
                </td>
            </tr>
            </tbody>
        </table>
        <?php echo $this->form()->closeTag() ?>
    </div>
<?php endif; ?>

<div class="tableWrapper">
    <table id="schedule" class="scheduleTable">
        <?php
        $end = $startDate->diff($endDate)->days + 2;
        for ($i = 0; $i < $end; $i++)
            echo '<colgroup></colgroup>';
        ?>
        <thead>
        <tr>
            <th style="width:60px"><?php echo $this->translate("Worker"); ?></th>
            <th style="width:45px"><?php echo $this->translate("Position"); ?></th>
            <?php
            do {
                $interval = $startDate->diff($endDate);
                echo "<th>" . \Application\Model\DateUtils::getTranslatedDate($startDate) . "</th>";
                $startDate->modify('+1 day');
            } while ($interval->days != 0);

            ?>
        </tr>
        </thead>
        <tbody>
        <?php
        foreach ($dates as $id => $dates):
            $decodedId = \Worker\Entity\Worker::decodeId($id);
            ?>
            <tr>
                <td style="padding:10px; background-color:#dedede"><span
                        class="workerName"><?php echo $decodedId["workerFullName"]; ?></span>
                <td style="padding:10px; background-color:#eeeeee"><span
                        class="workerPosition"><?php echo $decodedId["workerPosition"]; ?></span>
                </td>
                <?php
                foreach ($dates as $date => $entry):
                    ?>
                    <td>
                        <?php
                        if (!empty($entry)) {
                            if (is_array($entry)) {
                                foreach ($entry as $childEntry)
                                    echo $this->partial("entry", array("workerId" => $decodedId["workerId"], "entry" => $childEntry));
                            } else {
                                echo $this->partial("entry", array("workerId" => $decodedId["workerId"], "entry" => $entry));
                            }
                        } else {
                            echo $this->partial("entry", array("workerId" => $decodedId["workerId"], "entry" => "", "date" => $date));
                        }
                        ?>
                    </td>
                <?php endforeach; ?>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>

</div>
<?php if ($this->identity()): ?>
    <div id="editPanel">
        <?php
        $form->prepare();
        $form->setAttribute('action', $this->url('schedule_save'));
        $fieldset = $form->get('entry');
        echo $this->form()->openTag($form);
        echo $this->formHidden($fieldset->get('entryId'));
        ?>
        <div class="element">
            <?php
            echo $this->formLabel($fieldset->get('exception'));
            echo $this->formSelect($fieldset->get('exception'));
            echo $this->formElementErrors($fieldset->get('exception'), array('class' => 'formError'));
            ?>
        </div>
        <div class="element">
            <?php
            echo $this->formLabel($fieldset->get('startTime'));
            echo $this->formInput($fieldset->get('startTime'));
            echo $this->formElementErrors($fieldset->get('startTime'), array('class' => 'formError'));
            ?>
        </div>
        <div class="element">
            <?php
            echo $this->formLabel($fieldset->get('endTime'));
            echo $this->formInput($fieldset->get('endTime'));
            echo $this->formElementErrors($fieldset->get('endTime'), array('class' => 'formError'));
            ?>
        </div>
        <?php
        echo $this->form()->closeTag() ?>
        <span id="formEditDone"><?php echo $this->translate("Done"); ?></span>
        <span id="formEditRemove"><?php echo $this->translate("Remove"); ?></span>
    </div>
<?php endif; ?>