<?php
/**
 * @var \Zend\Form\Fieldset $fieldset
 */
$fieldset = $form->get('admin');
$form->prepare();
$form->setAttribute('action', $this->url('admins/add'));
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('security'));
?>
<table>
    <caption><?php echo $this->translate("Add a New Admin"); ?></caption>
    <thead>
    <tr>
        <th><?php echo $this->translate("Username"); ?>*</th>
        <th><?php echo $this->translate("Password"); ?>*</th>
        <th><?php echo $this->translate("Worker Profile"); ?></th>
        <th><?php echo $this->translate("Add"); ?></th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>
            <?php
            echo $this->formInput($fieldset->get('username'));
            echo $this->formElementErrors($fieldset->get('username'), array('class' => 'formError'));
            ?>
        </td>
        <td>
            <?php
            echo $this->formInput($fieldset->get('password'));
            echo $this->formElementErrors($fieldset->get('password'), array('class' => 'formError'));
            ?>
        </td>
        <td>
            <?php
            echo $this->formSelect($fieldset->get('relatedWorker'));
            echo $this->formElementErrors($fieldset->get('relatedWorker'), array('class' => 'formError'));
            ?>
        </td>
        <td>
            <?php echo $this->formSubmit($form->get('submit')->setValue($this->translate('Add'))); ?>
        </td>
    </tr>
    </tbody>
</table>
<?php echo $this->form()->closeTag() ?>