<div id="optionPanel">
    <span class="addAdminToggle">+ <?php echo $this->translate("Add Admin"); ?></span>
    <span id="saveChanges"><?php echo $this->translate("Save"); ?></span>
    <span id="resetChanges"><?php echo $this->translate("Reset"); ?></span>
</div>
<div id="addAdmin">
    <?php
    /**
     * @var \Zend\Form\Fieldset $fieldset
     */
    $fieldset = $form->get('admin');
    $form->prepare();
    $form->setAttribute('action', $this->url('admins/add'));
    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('security'));
    ?>
    <table>
        <caption><?php echo $this->translate("Add a New Admin"); ?></caption>
        <thead>
        <tr>
            <th><?php echo $this->translate("Username"); ?>*</th>
            <th><?php echo $this->translate("Password"); ?>*</th>
            <th><?php echo $this->translate("Worker Profile"); ?></th>
            <th><?php echo $this->translate("Add"); ?></th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>
                <?php
                echo $this->formInput($fieldset->get('username'));
                echo $this->formElementErrors($fieldset->get('username'), array('class' => 'formError'));
                ?>
            </td>
            <td>
                <?php
                echo $this->formInput($fieldset->get('password'));
                echo $this->formElementErrors($fieldset->get('password'), array('class' => 'formError'));
                ?>
            </td>
            <td>
                <?php
                echo $this->formSelect($fieldset->get('relatedWorker'));
                echo $this->formElementErrors($fieldset->get('relatedWorker'), array('class' => 'formError'));
                ?>
            </td>
            <td>
                <?php echo $this->formSubmit($form->get('submit')->setValue($this->translate('Add'))); ?>
            </td>
        </tr>
        </tbody>
    </table>
    <?php echo $this->form()->closeTag() ?>
</div>
<div class="tableWrapper">
    <table id="admins" class="editableTable">
        <?php
        for ($i = 0; $i < 4; $i++)
            echo '<colgroup></colgroup>';
        ?>
        <thead>
        <tr>
            <th class="invisible">Admin Id</th>
            <th><?php echo $this->translate("Username"); ?></th>
            <th><?php echo $this->translate("Password"); ?></th>
            <th><?php echo $this->translate("Related Worker"); ?></th>
            <th><?php echo $this->translate("Delete"); ?></th>
        </tr>
        </thead>
        <tbody>
        <?php
        /**
         * @var \Admin\Entity\Admin $admin
         */
        foreach ($this->admins as $admin): ?>
            <tr>
                <td class="adminAdminId invisible"><?php echo $admin->getAdminId(); ?></td>
                <td class="adminUsername editText"><?php echo $admin->getUsername(); ?></td>
                <td class="adminPassword editText">**********</td>
                <td class="adminRelatedWorker editText"><?php echo is_null($admin->getRelatedWorker()) ? '' : $admin->getRelatedWorker()->getFullName(); ?></td>
                <td class="delete">X</td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
<div id="editPanel">
    <textarea></textarea>
    <span id="editDone"><?php echo $this->translate("Done"); ?></span>
</div>