<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Schedule\Module'                          => __DIR__ . '/Module.php',
  'Schedule\Controller\ChangelogController'  => __DIR__ . '/src/Schedule/Controller/ChangelogController.php',
  'Schedule\Controller\ExceptionController'  => __DIR__ . '/src/Schedule/Controller/ExceptionController.php',
  'Schedule\Controller\IndexController'      => __DIR__ . '/src/Schedule/Controller/IndexController.php',
  'Schedule\Entity\Changelog'                => __DIR__ . '/src/Schedule/Entity/Changelog.php',
  'Schedule\Entity\Entry'                    => __DIR__ . '/src/Schedule/Entity/Entry.php',
  'Schedule\Entity\Exception'                => __DIR__ . '/src/Schedule/Entity/Exception.php',
  'Schedule\Factory\EntryAddFormFactory'     => __DIR__ . '/src/Schedule/Factory/EntryAddFormFactory.php',
  'Schedule\Factory\ExceptionAddFormFactory' => __DIR__ . '/src/Schedule/Factory/ExceptionAddFormFactory.php',
  'Schedule\Form\AddEntryFieldset'           => __DIR__ . '/src/Schedule/Form/AddEntryFieldset.php',
  'Schedule\Form\AddEntryForm'               => __DIR__ . '/src/Schedule/Form/AddEntryForm.php',
  'Schedule\Form\AddExceptionFieldset'       => __DIR__ . '/src/Schedule/Form/AddExceptionFieldset.php',
  'Schedule\Form\AddExceptionForm'           => __DIR__ . '/src/Schedule/Form/AddExceptionForm.php',
  'Schedule\Model\ExcelGenerator'            => __DIR__ . '/src/Schedule/Model/ExcelGenerator.php',
  'Schedule\Repository\ChangelogRepository'  => __DIR__ . '/src/Schedule/Repository/ChangelogRepository.php',
  'Schedule\Repository\EntryRepository'      => __DIR__ . '/src/Schedule/Repository/EntryRepository.php',
  'Schedule\Service\Changelog'               => __DIR__ . '/src/Schedule/Service/Changelog.php',
  'Schedule\Service\Entry'                   => __DIR__ . '/src/Schedule/Service/Entry.php',
  'Schedule\Service\Exception'               => __DIR__ . '/src/Schedule/Service/Exception.php',
);
