<table>
    <caption>Schedule</caption>
    <thead>
        <tr>
            <th>Workers - Days</th>
            <?php
            $days = date('t');
            for ($i = 1; $i < $days + 1; $i++):
                ?>
                <th><?php echo $i; ?></th>
            <?php endfor; ?>
        </tr>
    </thead>
    <tbody>
    <?php foreach($workers as $worker):?>
        <tr>
           <td><?php echo $worker->getFullName(); ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>