<div id="login">
    <h1><?php echo $this->translate("Login to Scheduler"); ?></h1>
    <?php
    $form->prepare();
    $form->setAttribute('action', $this->url('login'));
    $fieldset = $form->get('admin');

    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('security'));
    ?>
    <div class="element">
        <?php
        echo $this->formElementErrors($fieldset->get('username'), array('class' => 'formError'));
        echo $this->formLabel($fieldset->get('username'));
        echo $this->formInput($fieldset->get('username'));
        ?>
    </div>

    <div class="element">
        <?php
        echo $this->formElementErrors($fieldset->get('password'), array('class' => 'formError'));
        echo $this->formLabel($fieldset->get('password'));
        echo $this->formInput($fieldset->get('password'));
        ?>
    </div>

    <div class="element">
        <?php
        echo $this->formElementErrors($fieldset->get('remember'), array('class' => 'formError'));
        echo $this->formLabel($fieldset->get('remember'));
        echo $this->formCheckbox($fieldset->get('remember'));
        ?>
    </div>

    <?php echo $this->formSubmit($form->get('submit')->setValue($this->translate('Login'))); ?>

    <?php echo $this->form()->closeTag() ?>
</div>